"""AI Impact MCP server.

Exposes core.pipeline.analyze as granular MCP tools so an agentic IDE
(Antigravity, Cursor, Claude Code, ...) can check its own blast radius
mid-task, before declaring a code change complete. Every tool here is a
thin wrapper over the same core engine the CLI calls -- no analysis logic
lives in this file (see AI_Impact_Analyzer_PLAN.md section 5 & 14).

Run directly for local stdio testing:
    python -m mcp_impact.server
"""

from __future__ import annotations

from mcp.server.fastmcp import FastMCP

from core.models import ImpactReport
from core.pipeline import analyze
from core.serialize import report_to_dict

mcp = FastMCP("ai-impact")


def _run_analysis(repo_path: str, diff_ref: str | None, staged: bool) -> ImpactReport:
    return analyze(repo_path, diff_ref=diff_ref, staged=staged)


@mcp.tool()
def analyze_impact(repo_path: str, diff_ref: str | None = None, staged: bool = False) -> dict:
    """Full deterministic impact report for a diff: changed symbols, affected
    callers (tiered by hop distance), test-coverage gaps, and a HIGH/MEDIUM/LOW
    risk label with evidence for each finding.

    Args:
        repo_path: absolute path to the git repository to analyze.
        diff_ref: git ref to diff against (e.g. "HEAD~1", "main...HEAD").
                  Ignored if staged=True.
        staged: if true, analyze staged (git-added, uncommitted) changes instead.
    """
    report = _run_analysis(repo_path, diff_ref, staged)
    return report_to_dict(report)


@mcp.tool()
def get_affected_files(repo_path: str, diff_ref: str | None = None, staged: bool = False) -> list[dict]:
    """Just the affected-caller list across all findings -- cheaper than
    analyze_impact when an agent only needs to know 'what else might this touch',
    not the full risk breakdown.
    """
    report = _run_analysis(repo_path, diff_ref, staged)
    out: list[dict] = []
    for f in report.findings:
        for ac in f.affected_callers:
            out.append(
                {
                    "changed_symbol": f.changed_symbol.qualified_name,
                    "affected_symbol": ac.symbol.qualified_name,
                    "tier": ac.tier.value,
                    "file": ac.call_site.file,
                    "line": ac.call_site.lineno,
                }
            )
    return out


@mcp.tool()
def get_test_gaps(repo_path: str, diff_ref: str | None = None, staged: bool = False) -> list[dict]:
    """Just the test-coverage gaps -- cheaper than analyze_impact when an agent
    only needs to decide whether to write a test before finishing.
    """
    report = _run_analysis(repo_path, diff_ref, staged)
    out: list[dict] = []
    for f in report.findings:
        for gap in f.test_gaps:
            out.append({"symbol": f.changed_symbol.qualified_name, "file": f.changed_symbol.file, "gap": gap.description})
    return out


@mcp.tool()
def explain_finding(repo_path: str, symbol: str, diff_ref: str | None = None, staged: bool = False, provider: str = "gemini") -> dict:
    """Plain-language explanation of one finding, generated by an LLM from the
    already-computed evidence (the LLM never determines risk itself -- it can
    only phrase facts already present in the evidence dict).

    Requires GEMINI_API_KEY/GOOGLE_API_KEY or GROQ_API_KEY to be set. If no key
    is configured, or the provider call fails, this returns the deterministic
    evidence with an explicit "unavailable" status rather than silently
    returning nothing or fabricating prose -- the finding itself is always
    returned regardless of whether the AI layer is configured.
    """
    report = _run_analysis(repo_path, diff_ref, staged)
    match = next((f for f in report.findings if f.changed_symbol.qualified_name == symbol), None)
    if match is None:
        return {"error": f"no finding for symbol '{symbol}' in this diff"}

    from core.serialize import finding_to_dict

    finding_dict = finding_to_dict(match)

    from ai.explainer import ExplainerError, explain as explain_finding_text

    try:
        prose = explain_finding_text(finding_dict, provider=provider)
    except ExplainerError as exc:
        return {
            **finding_dict,
            "explanation": None,
            "explanation_status": f"AI explanation via '{provider}' unavailable: {exc}. "
            "The deterministic evidence above is authoritative and available now.",
        }

    return {**finding_dict, "explanation": prose, "explanation_status": "ok"}


if __name__ == "__main__":
    mcp.run()
